### ISSUE TITLE
HP-modification (healing/damage)

### ISSUE THREAD

**Issue by Kranosos** [Ne0Strix/open-realms#57]
# User Story
As a player, I want to be able to have my health points (HP) modified through healing or damage actions.

## Description
Players can have their HP increased or decreased by performing various in-game actions (e.g. playing cards, using abilities, taking damage from enemy team). The UI should reflect the changes in HP.

## Tasks:
- [x] (tbd) #58
- [x] #59

**Comment by Ne0Strix** [comment]
#58 and #59 closed by PR #84
