### ISSUE TITLE
Card Design

### ISSUE THREAD

**Issue by Benjamin-Dippold** [Ne0Strix/open-realms#6]
# User Story
As a user, I want to see which stats my cards have in my hand and the play-area matching the fantasy theme of the game.

# Description
Implement non-placeholder visuals for cards. Make sure that the graphics are published under the correct licence and refer/cite the source as necessary. Or we create them on our own.
The cards display the values of their underlying object (refer to #15). 

# Tasks:
- [x] #50
- [x] #51
- [x] #52
- [x] Integrate the new cards if #14 and #13 are already done.

**Comment by Ne0Strix** [comment]
Stats are already displayed on the bottom half of the card; the only bigger changes necessary are the images in the top half.
