### ISSUE TITLE
Dynamic Playserstat Datakeeping

### ISSUE THREAD

**Issue by sosaidi** [Ne0Strix/open-realms#7]
# User Story
As a player, I want to view my game statistics, because I want to see how well I am doing in the game.

## Description
Develop a feature that allows players to view their hero's statistics, such as remaining health, combat abilities, and gold.
Sperate from #80 since this only affects Number data as (Damange, Healing and Money).

## Tasks:
- [x] #46
- [ ] #47
- [x] #48
- [ ] #49

**Comment by Kranosos** [comment]
issue #47 and #49 are removed from this user story since there were conflicts with other user stories. The tasks are now handled in user story #92.
