### ISSUE TITLE
Startpage

### ISSUE THREAD

**Issue by sosaidi** [Ne0Strix/open-realms#9]
# User Story
As a player, I want to have an appealing and informative start page, because I want to get a good first impression of the game.

## Description
Develop a start page with an attractive design and important information, such as game instructions and options to start a new game. The start page should provide an overview of the game and its features, while also creating a positive first impression for the player. It should include a clear and concise menu with options to start a new game, continue an existing game, adjust settings, and view game instructions. The design of the start page should be visually appealing, with high-quality graphics and animations that engage the player. The start page should also be optimized for a variety of device sizes and resolutions.

## Tasks:
- [x] #38
- [x] #39
- [x] #40
- [x] #41

**Comment by Ne0Strix** [comment]
This builds on the logic of the current "startpage", but the flow should be improved; we might also want to skip the fancy animations.
