### ISSUE TITLE
Integrate Server/Client Design

### ISSUE THREAD

**Issue by Benjamin-Dippold** [Ne0Strix/open-realms#94]
# User Story
As a User, I want to play with another User on a different device.
## Description
We want the Server to be able to transmit gamestates or -actions and a client to receive them. The client should send (requests for) actions to the server (e.g. action validation, server as a service, which responsibility handles who, …).

## Tasks:
- [ ] #98
- [ ] #99
- [ ] #100

**Comment by Ne0Strix** [comment]
We identified the following information that needs to be communicated:

- Client ⇒ Server
- request:
- Card ID + target deck
- handcards ⇒ play card
- market deck ⇒ buy card
- play area ⇒ special ability (sacrifice, pickup, …)
- own guards ⇒ expend ability
- opponent guard ⇒ attack
- popup-response
- string
- end turn
- Server ⇒ Client
- action:
- Card ID + target deck + add/remove
- remove from deck
- add to deck
- player stat update
- HP
- turn-values
- choose from popup
- target-deck or effects
- server & client class to translate between socket events and game-sessions / presenter
- socket ⇔ client ⇔  (market/handcard/…)-presenters
- socket ⇔ server ⇔ game session

**Comment by Ne0Strix** [comment]
So basically the presenters and the game-session have to work with those limited 6 function calls. Client and server each have a handler that parse the message and translate the logic into equivalent actions and vice versa.

Next step for this issue is to implement the server + client-connector infrastructure on both sides and giving them basic communication functionality over a socket.

**Comment by Ne0Strix** [comment]
documented the communication in greater detail here:
https://github.com/Ne0Strix/open-realms/blob/feature/94-integrate-serverclient-design/Server_Hero_Realms/serverdoc.md

**Comment by Ne0Strix** [comment]
My thoughts so far regarding how to split up the responsibilities are commented in 06f7e87

**Comment by Ne0Strix** [comment]
| Event | MessageType | DataKeys |ServerAnswer | 
| :-- | :-- | :-- | :-- |
| Play card | `TOUCHED` | `CARD_ID`, `DECK` | `ADD_CARD`, `REMOVE_CARD` |
| End Turn | `END_TURN` | *none* | `UPDATE_PLAYER_STATS` |
