### ISSUE TITLE
Discovering/Calling out a Cheat-Attempt

### ISSUE THREAD

**Issue by Kranosos** [Ne0Strix/open-realms#96]
# User Story
As a Player, I want to see when other players are cheating.
## Description
There should be some indication visible (feelable?) to other players when someone is using the cheat function from #62 **and** a way to intervene (stop the cheater).

## Tasks:
- [ ] < List Tasks to be done >
- [ ] < To be filled during Sprintplanning >
- [ ] < … >

**Comment by Ne0Strix** [comment]
This was worked on together with @sosaidi in the corresponding cheating branch #127. Will be closed together with PR #127

**Comment by Ne0Strix** [comment]
Cheating now works by shaking the device. Once it's enabled, the ring of the coin-turnvalues turns white on both devices. The opponent can then tap that ring to uncover the attempt. If that happens before the turn is ended, all cards bought using the cheating feature are sacrificed (removed from the game) and a preset amount of damage (10) is dealt the cheating player. If the opponent wrongly accuses the player of cheating they're dealt another preset amount of damage
